mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.qin.springcloud.entities    # 所有Entity别名类所在包

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka #单机版
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  # 集群版

  instance:
#    修改eureka中的服务名称
    instance-id: payment8003
